#!/usr/bin/env bash

# These are not really aliases. Leave them here just for convenience.
export EDITOR='vim'
export PAGER='less'
export LESS='-RiF'
# -R --RAW-CONTROL-CHARS   : display raw control sequence for colors
# -i --ignore-case         : ignore case when searching unless contains uppercase letters
# -F --quit-if-one-screen
# -X --no-init             : disable sending termcap initialization and deinitialization strings
# -S --chop-long-lines     : chop instead of wrap long lines

# https://stackoverflow.com/a/29239609/7318257
# function if_os() { [[ $OSTYPE == *$1* ]]; }
function if_nix() {
    case "$OSTYPE" in
        *linux*|*hurd*|*msys*|*cygwin*|*sua*|*interix*) sys="gnu";;
        *bsd*|*darwin*) sys="bsd";;
        *sunos*|*solaris*|*indiana*|*illumos*|*smartos*) sys="sun";;
    esac
    [[ "${sys}" == "$1" ]];
}

if_nix gnu && alias ls='ls --color=auto -F'
if_nix bsd && alias ls='ls -GF'
alias grep='grep --color=auto'
alias egrep='egrep --color=auto'
alias fgrep='fgrep --color=auto'

# And here is a good website to modify it https://geoff.greer.fm/lscolors/
if_nix bsd && export LSCOLORS='exfxcxdxbxegedabagacad'
if_nix gnu && export LS_COLORS='di=34:ln=35:so=32:pi=33:ex=31:bd=34;46:cd=34;43:su=30;41:sg=30;46:tw=30;42:ow=30;43'


alias ..='cd ..'
alias ...='cd ../..'
alias ~='cd ~'

alias ll='ls -alhF'
# -a: all
# -l: long format
# -h: human readble size
# -F: show extra symbol for each type of file

function get_rc_file() {
    if grep bash <<<$SHELL > /dev/null; then
        echo "$HOME/.bashrc"
    elif grep zsh <<<$SHELL > /dev/null; then
        echo "$HOME/.zshrc"
    else
        return 1
    fi
}

function vimrc() {
    rcfile=$(get_rc_file)
    if [ -z "$rcfile" ]; then
        echo 'Unable to locate rcfile'
    else
        vim "$rcfile" && source "$rcfile"
    fi
}

function reloadrc() {
    rcfile=$(get_rc_file)
    if [ -z "$rcfile" ]; then
        echo 'Unable to locate rcfile'
    else
        source "$rcfile"
    fi
}

########################## vim ##########################
alias vimr='vim -R'

########################## npm ##########################
alias npmi='npm install'
alias npms='npm start'
alias npmd='npm run develop'
alias npmb='npm build'

########################## git ##########################
# Adapted from https://github.com/ohmyzsh/ohmyzsh/tree/master/plugins/git
alias gs='git status'

alias ga='git add'
alias gaa='git add -A'

alias gc='git commit -v'

alias gco='git checkout'

alias gp='git push'
alias gpf='git push --force-with-lease'
alias gpff='git push --force'

alias gf='git fetch --prune'
alias gu='git pull --prune'

alias grb='git rebase'
alias grbi='git rebase --interactive'
alias grbc='git rebase --continue'
alias grba='git rebase --abort'

alias gl='git l'
alias gla='git la'

alias gd='git diff'
alias gdc='git diff --cached'
alias gdw='git diff --word-diff'
alias gdcw='git diff --cached --word-diff'

alias gsw='git switch'
alias gbr='git branch'
alias gwt='git worktree'
alias gst='git stash'

alias gcleanff='git clean -fd'
alias grst='git reset'
alias gtrash='git stash push --include-untracked -m "trash"'


########################## pass ##########################
if if_nix bsd && which pass > /dev/null; then
    alias p='pass'
    alias psync='pass git fetch && pass git rebase && pass git push'
fi

if if_nix bsd && which trash > /dev/null; then
    alias trash='trash -F'
fi
