" --- TIPS ---
" Reload Vimrc File:  :so %
"                     :source %
"                     :source ~/.vimrc
"
" Set Color Column:   :set cc=80
"                     :set colorcolumn=80
" To Change Color:    :highlight ColorColumn ctermbg=0 guibg=lightgrey
" For More Columns:   :let &colorcolumn="80,".join(range(120,200),",")
"
" Suspend Vim:        ctrl-Z  to suppend
"                     $ fg    to resume, fg for foreground
" Start A New Shell:  :sh      :shell
"                     :!bash
" To Exit:            $ exit -or- ctrl-D
"
" Move By Screen Line: gj, gk

" Tabs:               :tabe[dit] <file>
"                     :tabp    :tabn
"                     gt       gT


" NOTE: In vimrc file, double quotes (
" --- Things to look into ---
" AUTOMATIC WORD WRAPING
" 'wm' = word margin
" 'tw' = textwidth
" 'fo' = formatoptions
"
" MAPPING
" :help :map-modes

" --- Must Haves ---
set nocompatible
filetype indent plugin on
syntax on


" --- Automatic Installation Vim-Plug ---
if empty(glob('~/.vim/autoload/plug.vim'))
  silent !curl -fLo ~/.vim/autoload/plug.vim --create-dirs
    \ https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
  autocmd VimEnter * PlugInstall --sync | source $MYVIMRC
endif


" --- Vim-Plug Packages ---
call plug#begin('~/.vim/plugged')
    Plug 'bling/vim-airline'
    Plug 'vim-airline/vim-airline-themes'
    Plug 'morhetz/gruvbox'
    Plug 'wakatime/vim-wakatime'
call plug#end()


" --- Themes ---
colorscheme default
let g:airline_powerline_fonts = 0  " This is the default
set background=light  " morhtz/gruvbox theme


" --- netrw Settings ---
let g:netrw_preview   = 1
let g:netrw_liststyle = 3
let g:netrw_winsize   = 30


" --- About Trailing Space ---
"      https://stackoverflow.com/questions/32588604/vim-airline-what-is-trailing1
"      Use  :AirlineToggleWhitespace  to toggle trailing space warnings
"      Use  :set invlist  to toggle
set list          " Display unprintable characters f12 - switches
set listchars=tab:▹\ ,trail:◦,extends:»,precedes:« " Unprintable chars mapping


" --- About Line Numbers ---
set number
set relativenumber
set cursorline                            " Highlight current line
highlight clear CursorLine                " Disables the underline
highlight CursorLine ctermbg=255          " cursor line color
highlight CursorLineNR ctermbg=lightBlue  " cursor line line number color
highlight MatchParen cterm=underline,bold ctermbg=none ctermfg=green   " matching paren color

" Only highlight line in current file
augroup CursorLine
    au!
    au VimEnter,WinEnter,BufWinEnter * setlocal cursorline
    au WinLeave * setlocal nocursorline
augroup END


" --- Enter -> New Line ---
map <Enter> o<ESC>
"map <S-Enter> O<ESC>

"map x to redirect it into blackhole register
nnoremap x "_x

" --- ShowChanges ---
" See  :h :DiffOrig  . This is also in |vimrc.example.vim|
if !exists(":DiffOrig")
  command DiffOrig vert new | set bt=nofile | r # | 0d_ | diffthis
          \ | wincmd p | diffthis
endif


" --- Compile and Run Commands ---
:command! C w || !set $1 $(echo "%" | sed 's/\.c//g'); clear; echo -e "$(date)\n"; gcc -Wall -o $1 "%" && ./$1 && rm $1
:command! Py w || !clear; echo -e "$(date)\n"; python3 "%"
:command! Pyi w || !clear; echo -e "$(date)\n"; python3 -i "%"
" --- Change ^w +/- Behavior ---
nnoremap <silent> <C-W>+ :exe "resize " . (winheight(0) * 5/4)<CR>
nnoremap <silent> <C-W>- :exe "resize " . (winheight(0) * 3/4)<CR>
nnoremap <silent> <C-W>> :exe "vertical resize " . (winwidth(0) * 6/5)<CR>
nnoremap <silent> <C-W>< :exe "vertical resize " . (winwidth(0) * 4/5)<CR>


" --- Add ^k, ^j Behavior ---
nnoremap <C-K> 3kzz
nnoremap <C-J> 3jzz

" --- Some Settings Found On Internet ---
" URL: http://vim.wikia.com/wiki/Example_vimrc
" Authors: http://vim.wikia.com/wiki/Vim_on_Freenode
"------------------------------------------------------------

" Vim with default settings does not allow easy switching between multiple files
" in the same editor window. Users can use multiple split windows or multiple
" tab pages to edit multiple files, but it is still best to enable an option to
" allow easier switching between files.
"
" One such option is the 'hidden' option, which allows you to re-use the same
" window and switch from an unsaved buffer without saving it first. Also allows
" you to keep an undo history for multiple files when re-using the same window
" in this way. Note that using persistent undo also lets you undo in multiple
" files even in the same window, but is less efficient and is actually designed
" for keeping undo history after closing Vim entirely. Vim will complain if you
" try to quit without saving, and swap files will keep you safe if your computer
" crashes.
set hidden

" Note that not everyone likes working this way (with the hidden option).
" Alternatives include using tabs or split windows instead of re-using the same
" window as mentioned above, and/or either of the following options:
" set confirm
" set autowriteall

" Better command-line completion
set wildmenu

" Show partial commands in the last line of the screen
set showcmd

" Show search results immediately, cursor will not be moved unless press enter

" Highlight searches (use <C-L> to temporarily turn off highlighting; see the
" mapping of <C-L> below)
" set hlsearch

" Modelines have historically been a source of security vulnerabilities. As
" such, it may be a good idea to disable them and use the securemodelines
" script, <http://www.vim.org/scripts/script.php?script_id=1876>.
" set nomodeline


"------------------------------------------------------------
" Usability options
"
" Searching
set ignorecase          " Docase insensitive ...
set smartcase           " ... unless there is one capital letter
set incsearch           " Incremental search

" Allow backspacing over autoindent, line breaks and start of insert action
set backspace=indent,eol,start

" When opening a new line and no filetype-specific indenting is enabled, keep
" the same indent as the line you're currently on. Useful for READMEs, etc.
set autoindent

" Always display the status line, even if only one window is displayed
set laststatus=2

" Display a confirm message instead of having error when having unsaved file.
set confirm

" Use visual bell instead of beeping when doing something wrong
" set t_vb to empty so it does not beep or flash.
set visualbell
set t_vb=

" Enable use of the mouse for all modes
set mouse=a

" Quickly time out on keycodes, but never time out on mappings
set notimeout ttimeout ttimeoutlen=200

" Use <F11> to toggle between 'paste' and 'nopaste'
""set pastetoggle=<F11>


"------------------------------------------------------------
" Indentation options
"
" Indentation settings for using 4 spaces instead of tabs.
" Do not change 'tabstop' from its default value of 8 with this setup.
set shiftwidth=4
set softtabstop=4
set expandtab

" Indentation settings for using hard tabs for indent.
"set shiftwidth=4
"set tabstop=4


"------------------------------------------------------------
" Useful mappings

" Map Y to act like D and C, i.e. to yank until EOL, rather than act as yy,
" which is the default
map Y y$

" Map <C-L> (redraw screen) to also turn off search highlighting until the
" next search
nnoremap <C-L> :nohl<CR><C-L>

